### PR TITLE
CA-210158: Only set mac-table-size on real (non-VLAN) bridges

### PR DESCRIPTION
**Pull request by robhoes**
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by johnelse** [comment]
:shipit:

**Comment by jonludlam** [comment]
Jolly good. Why doesn't it work with VLANs?

**Comment by robhoes** [comment]
@jonludlam Because `ovs-vsctl` pretends that a VLAN bridge is a bridge in the `add-br` call, but it reality the VLAN becomes a port on a "parent" bridge.

**Comment by jonludlam** [comment]
Nice :-(

**Pull request merged**
