### PR TITLE
CP-26923: Simplify Networkd logic by adding comments in modprobe conf…

### PR DESCRIPTION
**Pull request by xiewei20082008**
…ig file.

Signed-off-by: Wei Xie <wei.xie@citrix.com>

---
This change is [Reviewable](https://reviewable.io/reviews/xapi-project/xcp-networkd/131)

### CODE REVIEW

**Comment by xiewei20082008** [comment]
https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131

**Comment by xiewei20082008** [comment]
Based on the new design, the enabling logic in networkd_server can be super simple. Some functions related to Modprobe can be independent and modular, so I moved them all into Modprobe module.

**Comment by mseri** [comment]
The commit message should be expanded to contain the details of what this changes, how did things work and how they will work.

I have some preliminary comments, but this looks much better overall, I agree

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/network_utils.ml, line 1368 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r2yn-3XV-lgfu9Yzm:-L6r2yn-3XV-lgfu9Yzn:b-x8nqyk) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1368)):*
> ```OCaml
> 	options igb max_vfs = 7,7
> 
> 	This function's process: "igb" -> "VFs-param" -> "max_vfs"
> ```

This comment is not really clear to me.
Can you add a few simple example of calls that should return Some ... or None assuming the config file above?

---

*[lib/network_utils.ml, line 1371 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r-AoNUUhDYXtt1Kmw:-L6r-AoNUUhDYXtt1Kmx:btxok4o) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1371)):*
> ```OCaml
> 	*)
> 	let get_config_from_comments driver key =
> 		let lines = try Unixext.read_lines (getpath driver) with _ -> [] in
> ```

You don't need to keep lines separate to the rest of the block, you are ignoring the errors anyway. I'd suggest to avoid creating the new find map and simplify it as follows:

```ocaml
let get_config_from_comments driver key =
  try
    let open Xapi_stdext_std.Listext in
    Unixext.read_lines (getpath driver)
    |> List.filter_map (fun line ->
        if not Astring.String.is_prefix ~affix:("# " ^ key) line
        then None
        else
          match Astring.String.cut ~sep:":" (String.trim line) with
	  | None | Some (_, v) when String.trim v = "" -> None
          | Some (_, v) -> Some (String.trim v)
      )
    |> List.safe_hd
  with
  | err -> warn "get_config_from_comments %s %s failed with %s" driver key (Printexc.to_string err);
    None
```

---

*[lib/network_utils.ml, line 1387 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r3HxymsUODeCUFaw3:-L6r3HxymsUODeCUFaw4:b-390jb8) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1387)):*
> ```OCaml
> 
> 	(* this function not returning None means that the driver doesn't suppport sysfs *)
> 	let get_vf_param driver = get_config_from_comments driver "VFs-param"
> ```

Are you saying that `if support_sysfs driver = true then get_vf_param driver = None`? Can you add another line to explain why?

---

*[lib/network_utils.ml, line 1394 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4tzel6v8rSCifzSR:-L6r4tzel6v8rSCifzSS:bwoh7l8) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1394)):*
> ```OCaml
> 			| None -> None
> 			| Some v -> Some (int_of_string v)
> 		with _ -> None
> ```

Should we log the error?

---

*[lib/network_utils.ml, line 1401 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4wLLl1IuL9rQLrYr:-L6r4wLLl1IuL9rQLrYs:bwoh7l8) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1401)):*
> ```OCaml
> 			| None -> None
> 			| Some v -> Some (int_of_string v)
> 		with _ -> None
> ```

Should we log the error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-:-L6r90qDbsRKOBCbJyYC:b-md9hyh)*

**Comment by robhoes** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[lib/network_utils.ml, line 101 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vrQ1nyXPkw4LixivL:-L6vrQ1nyXPkw4LixivM:b-ko1sb4) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L101)):*
> ```OCaml
> 	check_n_run fork_script_internal script args
> 
> 	let rec find_map f = function
> ```

Indented too far.

A type annotation will make this easier to understand: `('a -> 'b option) -> 'a list -> 'b option`. Or just use `filter_map` as Marcello said.

---

*[lib/network_utils.ml, line 1334 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vukwYK2Eq3qK2MkDS:-L6vukwZKCQsMIpwM-gV:b-ewtqct) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1334)):*
> ```OCaml
> 		call_script ~log_successful_output:log !modinfo args
> 
> 	let is_param_array driver param_name =
> ```

Should we catch exceptions here and return `false`, or `Error`?

---

*[lib/network_utils.ml, line 1396 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vwzU-ZfeZ07O6p60r:-L6vwzU-ZfeZ07O6p60s:bjcqhnl) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1396)):*
> ```OCaml
> 		with _ -> None
> 
> 	let get_user_defined_maxvfs driver = 
> ```

These three function all read the same file again, and we tend to call all three more or less together...

---

*[lib/network_utils.ml, line 1413 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vyCeWXkdSt-4u3L7J:-L6vyCeWXkdSt-4u3L7K:b-y7ph5g) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1413)):*
> ```OCaml
> 		(* To enable SR-IOV via modprobe configuration, we add a line like `options igb max_vfs=7,7,7`
> 		into the configuration. This function is meant to generate the options like `7,7,7`. the `7` have to
> 		be repeated as many times as the number of devices with the same driver.
> ```

Well... not always anymore...

---

*[lib/network_utils.ml, line 1450 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vyvsj-gqv5ADp9z4S:-L6vyvsj-gqv5ADp9z4T:bl2j9d2) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1450)):*
> ```OCaml
> 				trimed_s
> 		in
> 		let lines = try Unixext.read_lines (getpath driver) with _ -> [] in
> ```

Now we are reading this file _again_?

---

*[networkd/network_server.ml, line 130 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vobeSkTUbIKn7cUI-:-L6vobeSkTUbIKn7cUI0:boi2vt6) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/networkd/network_server.ml#L130)):*
> ```OCaml
> 		if Sysfs.get_sriov_maxvfs dev = 0 then [] else ["sriov"]
> 
> 	let config_sriov ?(disable=false) dev  =
> ```

Minor: I'd have gone for a non-optional `enable` arg.

---

*[networkd/network_server.ml, line 137 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vp4niFHKQ5uF-6bJJ:-L6vp4niFHKQ5uF-6bJK:b-7en2on) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/networkd/network_server.ml#L137)):*
> ```OCaml
> 			debug "enable SR-IOV on a device: %s via modprobe" dev;
> 			begin
> 				if disable then Rresult.Ok 0 else Modprobe.get_maxvfs driver
> ```

We use `Result.Ok` elsewhere.

Minor: Perhaps `(if disable then Result.Ok 0 else Modprobe.get_maxvfs driver) >== fun numvfs ->` is a ilttle clearer?

---

*[networkd/network_server.ml, line 143 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6voHjdlk9F3GHUg5n6:-L6voHjdlk9F3GHUg5n7:b-qh81ij) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/networkd/network_server.ml#L143)):*
> ```OCaml
> 		| None ->
> 			debug "enable SR-IOV on a device: %s via sysfs" dev;
> 			let maxvfs = if disable then 0 else Sysfs.get_sriov_maxvfs dev in
> ```

Nitpick: `let numvfs`...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131)*

**Comment by xiewei20082008** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[lib/network_utils.ml, line 1371 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r-AoNUUhDYXtt1Kmw:-L6zWfkItMg_Sv2ACL6l:b-3qbywc) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1371)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

You don't need to keep lines separate to the rest of the block, you are ignoring the errors anyway. I'd suggest to avoid creating the new find map and simplify it as follows:

```ocaml
let get_config_from_comments driver key =
  try
    let open Xapi_stdext_std.Listext in
    Unixext.read_lines (getpath driver)
    |> List.filter_map (fun line ->
        if not Astring.String.is_prefix ~affix:("# " ^ key) line
        then None
        else
          match Astring.String.cut ~sep:":" (String.trim line) with
	  | None | Some (_, v) when String.trim v = "" -> None
          | Some (_, v) -> Some (String.trim v)
      )
    |> List.safe_hd
  with
  | err -> warn "get_config_from_comments %s %s failed with %s" driver key (Printexc.to_string err);
    None
```
</blockquote></details>

I was thinking `filter_map` may incur extra computation since there are only one target line, so I used find_map.
Looks like using lazy_list.filter_map can also avoid the  extra computation :)

---

*[lib/network_utils.ml, line 1387 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r3HxymsUODeCUFaw3:-L6zYuPOYQBQn1h5BOIj:b-k8uqke) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1387)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Are you saying that `if support_sysfs driver = true then get_vf_param driver = None`? Can you add another line to explain why?
</blockquote></details>

If a driver doesn't support sysfs, then we add `VF_param` into its driver modprobe configuration. Therefore, from XAPI's perspective, if Modprobe.get_vf_param is not None, the driver definitely  should use modprobe other than sysfs, and if Modprobe.get_vf_param is None, we just simple try sysfs.

I will add the explanation as comments into the code.

---

*[lib/network_utils.ml, line 1401 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4wLLl1IuL9rQLrYr:-L6zaIKWLtO7elOfFFFq:b-gf0c42) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1401)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Should we log the error?
</blockquote></details>

This doesn't mean an error - instead mean user didn't config a value, so we will use the default value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131)*

**Comment by xiewei20082008** [comment]
*[lib/network_utils.ml, line 1394 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4tzel6v8rSCifzSR:-L6zbRIHE-7vptmNtKpc:b-vlquyc) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1394)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Should we log the error?
</blockquote></details>

This is not an error. Returning None means it is a driver we will not use modprobe configuration method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131)*

**Comment by mseri** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[lib/network_utils.ml, line 1371 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r-AoNUUhDYXtt1Kmw:-L7-2UF3GH2xkioSDv3v:bvol9y4) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1371)):*
<details><summary><i>Previously, xiewei20082008 (Wei Xie) wrote…</i></summary><blockquote>

I was thinking `filter_map` may incur extra computation since there are only one target line, so I used find_map.
Looks like using lazy_list.filter_map can also avoid the  extra computation :)
</blockquote></details>

Even in this case, given that it is only used there, you can move the `find_map` function as helper inside this function, bring the `read_lines` inside the `try` block, and simplify the flow  as above (you just won't need the `safe_hd` and stdext. I don't like the use of `List.nth` for example and I'd rathed use `cut`, as above, that is safe and more declarative.

---

*[lib/network_utils.ml, line 1387 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r3HxymsUODeCUFaw3:-L7-3KQV-3zAbVYKYILs:b-zcjvte) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1387)):*
<details><summary><i>Previously, xiewei20082008 (Wei Xie) wrote…</i></summary><blockquote>

If a driver doesn't support sysfs, then we add `VF_param` into its driver modprobe configuration. Therefore, from XAPI's perspective, if Modprobe.get_vf_param is not None, the driver definitely  should use modprobe other than sysfs, and if Modprobe.get_vf_param is None, we just simple try sysfs.

I will add the explanation as comments into the code.
</blockquote></details>

Thanks

---

*[lib/network_utils.ml, line 1394 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4tzel6v8rSCifzSR:-L7-3L0y7uJVOWg9pDJl:b-1xiu76) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1394)):*
<details><summary><i>Previously, xiewei20082008 (Wei Xie) wrote…</i></summary><blockquote>

This is not an error. Returning None means it is a driver we will not use modprobe configuration method.
</blockquote></details>

I understand this, I thought that a debug line could be useful for example to see if there was a typo or something in the configuration instead of being completely silent. But if this clutters too much the logs, let's keep it as it is

---

*[lib/network_utils.ml, line 1401 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4wLLl1IuL9rQLrYr:-L7-3_lLAcB4oCsjP5B6:b-be0m7d) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1401)):*
<details><summary><i>Previously, xiewei20082008 (Wei Xie) wrote…</i></summary><blockquote>

This doesn't mean an error - instead mean user didn't config a value, so we will use the default value.
</blockquote></details>

I understand this, but see my reply above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131)*

**Comment by xiewei20082008** [comment]
Done.

---

Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[lib/network_utils.ml, line 101 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vrQ1nyXPkw4LixivL:-L79VNCW1PZUd-B6qhcY:b-x25jy9) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L101)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Indented too far.

A type annotation will make this easier to understand: `('a -> 'b option) -> 'a list -> 'b option`. Or just use `filter_map` as Marcello said.
</blockquote></details>

To avoid read the config file too many times. I changed to use `filter_map` as Marcello said - read (key *value) list from comments at one time.

---

*[lib/network_utils.ml, line 1334 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vukwYK2Eq3qK2MkDS:-L79WPsFd4nknZRMJ4V2:b-qkxk8q) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1334)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Should we catch exceptions here and return `false`, or `Error`?
</blockquote></details>

Done. I suppose the only position to raise exception in during the `modinfo` command execution, and if it happens, then it is definitely an Error not a false.

---

*[lib/network_utils.ml, line 1368 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r2yn-3XV-lgfu9Yzm:-L79WkJjGdcVe6sIwBlJ:b5gwggr) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1368)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

This comment is not really clear to me.
Can you add a few simple example of calls that should return Some ... or None assuming the config file above?
</blockquote></details>

Actually I was intend to add an example. :) Hope it is more clear now.

---

*[lib/network_utils.ml, line 1371 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r-AoNUUhDYXtt1Kmw:-L79WxcSpHbDJwjNWwvI:bnreiw2) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1371)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

Even in this case, given that it is only used there, you can move the `find_map` function as helper inside this function, bring the `read_lines` inside the `try` block, and simplify the flow  as above (you just won't need the `safe_hd` and stdext. I don't like the use of `List.nth` for example and I'd rathed use `cut`, as above, that is safe and more declarative.
</blockquote></details>

Filter_map is fantastic. Thank you.

---

*[lib/network_utils.ml, line 1394 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4tzel6v8rSCifzSR:-L79X5yyJlmgtS8dAMHi:b16ubr) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1394)):*
<details><summary><i>Previously, xiewei20082008 (Wei Xie) wrote…</i></summary><blockquote>

Ah, I get your point - that makes sense. It will not clutter too much logs. I can add logs for it. Thank  you.
</blockquote></details>

I moved this function and the next function inside `get_maxvfs` and added return Error.

---

*[lib/network_utils.ml, line 1396 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vwzU-ZfeZ07O6p60r:-L79XNbdTPCXMY9bhU9W:b-k3bi7d) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1396)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

These three function all read the same file again, and we tend to call all three more or less together...
</blockquote></details>

I was a lazy computer language translator - I just copied the logic from Simon's Python Demo. :joy: [https://issues.citrite.net/secure/attachment/1327248/sriov.py].

I think it is much better now - read all key value pair at one time.

---

*[lib/network_utils.ml, line 1401 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6r4wLLl1IuL9rQLrYr:-L79YKTAUi5MrJc6qvKl:b-4qlj6r) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1401)):*
<details><summary><i>Previously, mseri (Marcello Seri) wrote…</i></summary><blockquote>

I understand this, but see my reply above
</blockquote></details>

Replied above.

---

*[lib/network_utils.ml, line 1413 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vyCeWXkdSt-4u3L7J:-L79YOIsUo-nbUYlbUWw:b-rtwc7f) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1413)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Well... not always anymore...
</blockquote></details>

Done. Changed comments.

---

*[lib/network_utils.ml, line 1450 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vyvsj-gqv5ADp9z4S:-L79YSH94KMwQtOBKBHK:bcrmzn9) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1450)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Now we are reading this file _again_?
</blockquote></details>

Do you think read twice is reasonable? or I have to keep all contents in network_server.ml.

---

*[networkd/network_server.ml, line 130 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vobeSkTUbIKn7cUI-:-L79YqV8pgPpABFOGZhS:b-896fix) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/networkd/network_server.ml#L130)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Minor: I'd have gone for a non-optional `enable` arg.
</blockquote></details>

Done.

---

*[networkd/network_server.ml, line 137 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vp4niFHKQ5uF-6bJJ:-L79YqyNnqiAVprbye3G:b-896fix) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/networkd/network_server.ml#L137)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

We use `Result.Ok` elsewhere.

Minor: Perhaps `(if disable then Result.Ok 0 else Modprobe.get_maxvfs driver) >== fun numvfs ->` is a ilttle clearer?
</blockquote></details>

Done.

---

*[networkd/network_server.ml, line 143 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6voHjdlk9F3GHUg5n6:-L79YlpOaRuCOWG4ZAP2:b-896fix) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/networkd/network_server.ml#L143)):*
<details><summary><i>Previously, robhoes (Rob Hoes) wrote…</i></summary><blockquote>

Nitpick: `let numvfs`...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-:-L79VLmXsxsudn1AjtXK:b-896fix)*

**Comment by robhoes** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[lib/network_utils.ml, line 1450 at r1](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-L6vyvsj-gqv5ADp9z4S:-L79abJy2wANQV8sYBPk:bnkkgxg) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1450)):*
<details><summary><i>Previously, xiewei20082008 (Wei Xie) wrote…</i></summary><blockquote>

Do you think read twice is reasonable? or I have to keep all contents in network_server.ml.
</blockquote></details>

OK, you've gone from 4 to 2 now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-:-L79bRZQOFjbIK1lQy8v:bnfp4nl)*

**Comment by krizex** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[lib/network_utils.ml, line 1366 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L7Nrsqo8GsRTlO6c6lO:-L7Nrsqo8GsRTlO6c6lP:bhxiutj) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1366)):*
> ```OCaml
> 	# VFs-maxvfs-by-default: 7
> 	# VFs-maxvfs-by-user: X
> 	options igb max_vfs = 7,7
> ```

Should be `options igb max_vfs=7,7`, remove the space besides `=`

---

*[lib/network_utils.ml, line 1373 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L7NmuYiBkNCRe9msRWX:-L7NmuYiBkNCRe9msRWY:b-mchgv7) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1373)):*
> ```OCaml
> 		let lines = try Unixext.read_lines (getpath driver) with _ -> [] in
> 		try
> 			find_map (fun x -> begin
> ```

I think the `begin` and `end` is needless here.

---

*[lib/network_utils.ml, line 1401 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L6r4wLLl1IuL9rQLrYr:-L7NpJ435vBwuiZpliTM:b-fadxmi) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1401)):*
<details><summary><i>Previously, xiewei20082008 (Wei Xie) wrote…</i></summary><blockquote>

Replied above.
</blockquote></details>

I prefer extract the similar logic of  `get_default_maxvfs` and `get_user_defined_maxvfs` into a helper function.

---

*[lib/network_utils.ml, line 1444 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L7NrSEs7PrRDchkNbTy:-L7NrSEs7PrRDchkNbTz:b3e6hdk) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1444)):*
> ```OCaml
> 			let trimed_s = String.trim s in
> 			if Re.execp (Re_perl.compile_pat ("options[ \t]+" ^ driver)) trimed_s then
> 				let driver_options = Re.split (Re_perl.compile_pat "[ \t]+") trimed_s in
> ```

Per this implementation, the example of `options igb max_vfs = 7,7 (Notes: The lower of the above two value will be used. The parameter may be an array, each number is associated with an interface.)` in the design doc http://www.uk.xensource.com/~weix/xs-documents/designs/networking-sriov/#dom0-part-design-design should be update to
```
options igb max_vfs=7,7 (Notes: The lower of the above two value will be used. The parameter may be an array, each number is associated with an interface.)
```
(remove the space besides `=`).
The comments in this file should be updated corresponding, see above comments.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131)*

**Comment by xiewei20082008** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[lib/network_utils.ml, line 1366 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L7Nrsqo8GsRTlO6c6lO:-L7NyCF41xFB8_zVfpQm:b-896fix) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1366)):*
<details><summary><i>Previously, krizex (Yang Qian) wrote…</i></summary><blockquote>

Should be `options igb max_vfs=7,7`, remove the space besides `=`
</blockquote></details>

Done.

---

*[lib/network_utils.ml, line 1373 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L7NmuYiBkNCRe9msRWX:-L7NyDa8688vOc2zaXGL:bwzdwff) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1373)):*
<details><summary><i>Previously, krizex (Yang Qian) wrote…</i></summary><blockquote>

I think the `begin` and `end` is needless here.
</blockquote></details>

You were looking at an old version.

---

*[lib/network_utils.ml, line 1401 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L6r4wLLl1IuL9rQLrYr:-L7NyIOP-V4Gi_yat0ue:b-nkj0xn) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1401)):*
<details><summary><i>Previously, krizex (Yang Qian) wrote…</i></summary><blockquote>

I prefer extract the similar logic of  `get_default_maxvfs` and `get_user_defined_maxvfs` into a helper function.
</blockquote></details>

The same with above.

---

*[lib/network_utils.ml, line 1444 at r1](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131#-L7NrSEs7PrRDchkNbTy:-L7NybEhDy2_LBSUUQEf:b54gpzs) ([raw file](https://github.com/xapi-project/xcp-networkd/blob/3bea73b9ed7c353e26845860331be64b4771df27/lib/network_utils.ml#L1444)):*
<details><summary><i>Previously, krizex (Yang Qian) wrote…</i></summary><blockquote>

Per this implementation, the example of `options igb max_vfs = 7,7 (Notes: The lower of the above two value will be used. The parameter may be an array, each number is associated with an interface.)` in the design doc http://www.uk.xensource.com/~weix/xs-documents/designs/networking-sriov/#dom0-part-design-design should be update to
```
options igb max_vfs=7,7 (Notes: The lower of the above two value will be used. The parameter may be an array, each number is associated with an interface.)
```
(remove the space besides `=`).
The comments in this file should be updated corresponding, see above comments.

</blockquote></details>

Ok. I will get the design updated.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/xapi-project/xcp-networkd/131)*

**Comment by krizex** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/xapi-project/xcp-networkd/131#-:-L7NyqDmUQ6TDkWk1tJ2:bnfp4nl)*

**Pull request merged**
