### PR TITLE
Use a switch `--xapi` to call fcoe driver

### PR DESCRIPTION
**Pull request by sharady**
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by sharady** [comment]
@xen-git test this please

**Comment by sharady** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
As discussed with @sharady on slack, this should be split into two commits - one for the `--xapi` change, and one for the change in the path of the FCOE driver. Otherwise this looks good.

**Comment by sharady** [comment]
Thanks @johnelse for the review :)
I have split the changes into 2 commits, Please have a look.

**Comment by johnelse** [comment]
Looks good!

**Pull request merged**
