### PR TITLE
CA-276745: Fix Networkd.Sysfs.get_driver_name

### PR DESCRIPTION
**Pull request by xiewei20082008**
Signed-off-by: Wei Xie <wei.xie@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Interesting... I suspect that there was a kernel change that broke this some time ago, but we didn't notice (this `get_driver_name` function is currently only used in `handle_vlan_bug_workaround`, which isn't important in practice).

**Comment by robhoes** [comment]
Hmm... Travis is broken...

**Comment by robhoes** [comment]
```
Error: Package: ocaml-xen-api-client-devel-1.0.0-1.el7.centos.x86_64 (xs)
           Requires: xapi-client-devel
```

**Comment by xiewei20082008** [comment]
Yes... It is broken. 🤕

**Comment by robhoes** [comment]
@gaborigloi is fixing Travis now.

**Comment by gaborigloi** [comment]
Works now 😄

**Comment by robhoes** [comment]
Beautiful.

**Comment by gaborigloi** [comment]
PR to fix it: https://github.com/xenserver/upload-scripts/pull/23

**Pull request merged**
