### PR TITLE
CP-15312: Remove harmless exception from toolstack startup

### PR DESCRIPTION
**Pull request by koushikcgit**
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
The `Network_utils` module is meant to be a library of lower-level Linux networking functions and should not just ignore exceptions. The higher-level `Network_server` module uses `Network_utils` and may choose to catch and discard exceptions.

In fact, the `Interface.make_config` function calls `set_ipv6_conf` (which calls `Dhcp6.start` and `Dhcp6.stop` from `Network_utils`) and drops the exception already. So what exactly is this patch doing?

**Comment by koushikcgit** [comment]
@robhoes : Even though the exceptions were being dropped, the xensource.log still had the raise exception logged which is what needed to be removed. I was trying to do that in this patch.

**Comment by robhoes** [comment]
Unfortunately, `call_script` logs the error even if you catch the exception.

**Comment by robhoes** [comment]
After a bit of looking around, I conclude that errors are logged from `set_ipv6_conf` in two places:
- By `call_script`, which reports that it cannot find the `dhcp6c` program.
- By `Debug.with_thread_associated`, which logs the backtrace.

Koushik's patch avoids the latter. However, I'm still not happy with the approach. Much better would be to actually remove the cause of the exception. It turns out that all uses of dhcp6c can now be replaced by calls to dhclient (using the `-6` option). The `Dhclient` module in network_utils.ml already has code for this. I therefore propose to fix the issue by switching over to `Dhclient` and drop the `Dhcp6c` module, in a new PR.

**Comment by robhoes** [comment]
I'll close this PR based on the above.

**Pull request closed without merging**
